image: renaudboulard/android-docker

stages:
  - build
  - quality

before_script:
  - chmod +x gradlew
  - echo $ANDROID_HOME
  - export JAVA_HOME=$JAVA_HOME
  - echo $JAVA_HOME

Compile:
  stage: build
  script:
    - ./gradlew :app:assembleDebug

checkstyle:
  stage: quality
  script:
    - ./gradlew :locky:checkstyle

Lint:
  stage: quality
  script:
    - ./gradlew :locky:lint

Unit Test:
  stage: quality
  script:
    - ./gradlew :locky:testDebugUnitTest
  dependencies:
    - Compile